version: '3.8'

services:
  oatiback:
    build: ./back/app
    container_name: oatiback
    volumes:
      - ./back/app:/app
    networks:
      - proxy
    environment:
      - DATABASE_URL=
  oatifront:
    build: ./front
    expose:
      - 5000
    volumes:
      - ./front:/usr/src/app
    ports:
      - 80:3000
    networks:
      -proxy
networks:
  proxy:
    external: true